name: Napi script futtatás masodik resz

on:
  schedule:
    - cron: '0 10 * * *'  # 13:00 magyar idő szerint (11:00 UTC)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests supabase

      - name: Run scripts in order
        run: |
         python allasok.py újpest 25
         python allasok.py kispest 25
         python allasok.py budaörs 25
          python allasok.py gödöllő 25
          python allasok.py cegléd 25
          python allasok.py győr
          python allasok.py sopron
          python allasok.py zalaegerszeg
          python allasok.py szombathely
          python allasok.py kaposvár
          python allasok.py pécs
          python allasok.py szekszárd
          python allasok.py kecskemét
          python allasok.py szeged
          python allasok.py békéscsaba
          python allasok.py miskolc
          python allasok.py nyíregyháza
          python allasok.py debrecen
