name: Napi script futtatás

on:
  schedule:
    - cron: '0 11 * * *'  # 13:00 magyar idő szerint (11:00 UTC)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests supabase

      - name: Run scripts in order
        run: |
          python bonyhad50.py
          python pecs50.py
          python szekszard50.py
          python barcs50.py
          python paks50.py
