      - name: Run scripts in order
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            TABLE_NAME: ${{ secrets.TABLE_NAME }}
            LOGIN_URL: ${{ secrets.LOGIN_URL }}
            SEARCH_URL: ${{ secrets.SEARCH_URL }}
        run: |
          városok=(
            "újpest 25"
            "kispest 25"
            "budaörs 10"
            "gödöllő 25"
            "cegléd"
            "győr"
            "sopron"
            "zalaegerszeg 25"
            "szombathely 25"
            "kaposvár"
            "pécs"
            "szekszárd"
            "kecskemét"
            "szeged"
            "békéscsaba"
            "miskolc"
            "nyíregyháza"
            "debrecen"
            "eger"
            "szolnok"
            "salgótarján"
          )

          for sor in "${városok[@]}"; do
            echo "Indul: $sor"
            timeout 1800 python allasok.py $sor || echo "$sor hibára futott"
            sleep 12
          done
        shell: bash  # ← FONTOS: ezt ide, közvetlenül a `run:` alá írd
