name: Napi script futtatás

on:
  schedule:
    - cron: '0 11 * * *'  # 13:00 magyar idő szerint (11:00 UTC)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests supabase

      - name: Run scripts in order
        run: |
           run: |
          python allasok.py újpest 25 || echo "újpest hibára futott"
          sleep 12
          python allasok.py kispest 25 || echo "kispest hibára futott"
          sleep 12
          python allasok.py budaörs 10 || echo "budaörs hibára futott"
          sleep 12
          python allasok.py gödöllő 25 || echo "gödöllő hibára futott"
          sleep 12
          python allasok.py cegléd || echo "cegléd hibára futott"
          sleep 12
          python allasok.py győr || echo "győr hibára futott"
          sleep 12
          python allasok.py sopron || echo "sopron hibára futott"
          sleep 12
          python allasok.py zalaegerszeg 25 || echo "zalaegerszeg hibára futott"
          sleep 12
          python allasok.py szombathely 25 || echo "szombathely hibára futott"
          sleep 12
          python allasok.py kaposvár || echo "kaposvár hibára futott"
          sleep 12
          python allasok.py pécs || echo "pécs hibára futott"
          sleep 12
          python allasok.py szekszárd || echo "szekszárd hibára futott"
          sleep 12
          python allasok.py kecskemét || echo "kecskemét hibára futott"
          sleep 12
          python allasok.py szeged || echo "szeged hibára futott"
          sleep 12
          python allasok.py békéscsaba || echo "békéscsaba hibára futott"
          sleep 12
          python allasok.py miskolc || echo "miskolc hibára futott"
          sleep 12
          python allasok.py nyíregyháza || echo "nyíregyháza hibára futott"
          sleep 12
          python allasok.py debrecen || echo "debrecen hibára futott"
          sleep 12
          python allasok.py eger || echo "eger hibára futott"
          sleep 12
          python allasok.py szolnok || echo "szolnok hibára futott"
          sleep 12
          python allasok.py salgótarján || echo "salgótarján hibára futott"

