name: Napi script futtatás

on:
  schedule:
    - cron: '0 11 * * *'  # 13:00 magyar idő szerint (11:00 UTC)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    
    env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        TABLE_NAME: ${{ secrets.TABLE_NAME }}
        LOGIN_URL: ${{ secrets.LOGIN_URL }}
        SEARCH_URL: ${{ secrets.SEARCH_URL }}
        TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
        TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests supabase python-dotenv typesense aiohttp
          pip install pandas numpy  # Opcionális, ha szükséges

      - name: Run scripts in order
        run: |
          echo "Bács-Kiskun elinditva"
          timeout 1800 python allasok.py Bács-Kiskun megye|| echo "Bács-Kiskun hibára futott"
          sleep 20
          echo "Baranya elinditva"
          timeout 1800 python allasok.py Baranya megye || echo "Baranya hibára futott"
          sleep 20
          echo "Borsod-Abaúj-Zemplén  elinditva"
          timeout 1800 python allasok.py Borsod-Abaúj-Zemplén megye || echo "Borsod-Abaúj-Zemplén hibára futott"
          sleep 20
          echo "Békés elinditva"
          timeout 1800 python allasok.py Békés megye || echo "Békés hibára futott"
          sleep 20
          echo "Csongrád megye elinditva"
          timeout 1800 python allasok.py Csongrád megye || echo "Csongrád hibára futott"
          sleep 20
          echo "Fejér elinditva"
          timeout 1800 python allasok.py Fejér megye || echo "Fejér hibára futott"
          sleep 20
          echo "Győr-Moson-Sopron  elinditva"
          timeout 1800 python allasok.py Győr-Moson-Sopron megye || echo "Győr-Moson-Sopron  hibára futott"
          sleep 20
          echo "Hajdú-Bihar vármegye elinditva"
          timeout 1800 python allasok.py Hajdú-Bihar megye || echo "Hajdú-Bihar vármegye hibára futott"
          sleep 20
          echo "Heves elinditva"
          timeout 1800 python allasok.py Heves megye || echo "Heves hibára futott"
          sleep 20
          echo "Jász-Nagykun-Szolnok elinditva"
          timeout 1800 python allasok.py Jász-Nagykun-Szolnok megye || echo "Jász-Nagykun-Szolnok hibára futott"
          sleep 20
          echo "Komárom-Esztergom elinditva"
          timeout 1800 python allasok.py Komárom-Esztergom megye || echo "Komárom-Esztergom hibára futott"
          sleep 20
          echo "Nógrád elinditva"
          timeout 1800 python allasok.py Nógrád megye || echo "Nógrád hibára futott"
          sleep 20
          echo "Pest megye elinditva"
          timeout 1800 python allasok.py Pest megye|| echo "Pest megye hibára futott"
          sleep 20
          echo "Somogy elinditva"
          timeout 1800 python allasok.py Somogy megye || echo "Somogy hibára futott"
          sleep 20
          echo "Szabolcs-Szatmár-Bereg elinditva"
          timeout 1800 python allasok.py Szabolcs-Szatmár-Bereg megye || echo "Szabolcs-Szatmár-Bereg hibára futott"
          sleep 20
          echo "Tolna elinditva"
          timeout 1800 python allasok.py Tolna megye || echo "Tolna megye hibára futott"
          sleep 20
          echo "Vas elinditva"
          timeout 1800 python allasok.py Vas megye || echo "Vas hibára futott"
          sleep 20
          echo "Veszprém elinditva"
          timeout 1800 python allasok.py Veszprém megye || echo "Veszprém hibára futott"
          sleep 20
          echo "Zala elinditva"
          timeout 1800 python allasok.py Zala megye || echo "Zala hibára futott"
          sleep 18
          echo "typesense szinkron elinditva"
          timeout 1800 python szinkron.py  || echo "szinkronizalas hibára futott"

