name: Napi script futtatás masodik resz

on:
  schedule:
    - cron: '0 10 * * *'  # 13:00 magyar idő szerint (11:00 UTC)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests supabase

      - name: Run scripts in order
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
            TABLE_NAME: ${{ secrets.TABLE_NAME }}
            LOGIN_URL: ${{ secrets.LOGIN_URL }}
            SEARCH_URL: ${{ secrets.SEARCH_URL }}
        run: |
         python allasok.py újpest 25 || echo "újpest hibara futott"
         python allasok.py kispest 25 || echo "kispest hibara futott"
         python allasok.py budaörs 10 || echo "budaörs hibara futott"
          python allasok.py gödöllő 25 || echo "gödöllő hibara futott"
          python allasok.py cegléd || echo "cegléd hibara futott"
          python allasok.py győr || echo "győr hibara futott"
          python allasok.py sopron || echo "sopron hibara futott"
          python allasok.py zalaegerszeg 25 || echo "zalaegerszeg hibara futott"
          python allasok.py szombathely 25 || echo "szombathely hibara futott"
          python allasok.py kaposvár || echo "kaposvár hibara futott"
          python allasok.py pécs || echo "pécs hibara futott"
          python allasok.py szekszárd || echo "szekszárd hibara futott"
          python allasok.py kecskemét || echo "kecskemét hibara futott"
          python allasok.py szeged || echo "szeged hibara futott"
          python allasok.py békéscsaba || echo "békéscsaba hibara futott"
          python allasok.py miskolc || echo "miskolc hibara futott"
          python allasok.py nyíregyháza || echo "nyíregyháza hibara futott"
          python allasok.py debrecen || echo "debrecen hibara futott"
          python allasok.py eger || echo "eger hibara futott"
          python allasok.py szolnok || echo "szolnok hibara futott"
          python allasok.py salgótarján || echo "salgótarján hibara futott"
